# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coinr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coinr
    pod 'Firebase', '~> 4.0'
    pod 'FirebaseCore', '~> 4.0'
    pod 'FirebaseAuth', '~> 4.0'
    pod 'FirebaseDatabase', '~> 4.0'
    pod 'Charts'

  target 'CoinrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoinrUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
